USE bookstore;

INSERT INTO Book(title,genre,pubYear,price,inventory,bookDescription,createdAt,updatedAt,AuthorId) VALUES
('28 Summers','NYT',2020,28,4,'A relationship that started in 1993 between Mallory Blessing and Jake McCloud comes to light while she is on her deathbed and his wife runs for president.',sysdate(),sysdate(),1),
('The Vanishing Half','NYT',2020,27,8,'The lives of twin sisters who run away from a Southern Black community at age 16 diverge as one returns and the other takes on a different racial identity but their fates intertwine.',sysdate(),sysdate(),2),
('The Room Where it Happened','NYT',2020,32.50,7,'The former national security advisor gives his account of the 17 months he spent working for President Trump.',sysdate(),sysdate(),3),
('White Fragility','NYT',2018,16,4,'Historical and cultural analyses on what causes defensive moves by white people and how this inhibits cross-racial dialogue.',sysdate(),sysdate(),4),
('Where the Crawdads Sing','NYT',2018,26,7,'In a quiet town on the North Carolina coast in 1969, a young woman who survived alone in the marsh becomes a murder suspect.',sysdate(),sysdate(),5),
('Camino Winds','NYT',2020,28.95,9,'The line between fact and fiction becomes blurred when an author of thrillers is found dead after a hurricane hits Camino Island.',sysdate(),sysdate(),6),
('How to be an Antiracist','NYT',2019,27,3,'A primer for creating a more just and equitable society through identifying and opposing racism.',sysdate(),sysdate(),7),
('Little Fires Everywhere','NYT',2017,17,5,'An artist with a mysterious past and a disregard for the status quo upends a quiet town outside Cleveland.',sysdate(),sysdate(),8),
('So You Want To Talk About Race','NYT',2019,16.99,2,'A look at the contemporary racial landscape of the United States',sysdate(),sysdate(),9),
('To Kill A Mockingbird','Classic',1960,15.99,10,'In "To Kill a Mockingbird", author Harper Lee uses memorable characters to explore civil rights and racism in the segregated Southern United States of the 1930s.',sysdate(),sysdate(),10),
('Anne Of Green Gables','Classic',1908,5.99,8,'Anne of Green Gables is the story of a young orphan girl, Anne, who is mistakenly delivered to an older couple looking to adopt a boy to work on their farm.',sysdate(),sysdate(),11),
('The Call of the Wild','Classic',1903,12.95,6,'Based on Jack London''s experiences as a gold prospector in the Canadian wilderness.',sysdate(),sysdate(),12),
('Pride And Prejudice','Classic',1913,9.00,9,'A classic of English literature, written with incisive wit and superb character delineation.',sysdate(),sysdate(),13),
('The Great Gatsby','Classic',1925,17.00,4,'The story is of the fabulously wealthy Jay Gatsby and his new love for the beautiful Daisy Buchanan.',sysdate(),sysdate(),14),
('Wuthering Heights','Classic',1847,8.00,7,'Wuthering Heights is a classic gothic horror/romance novel.',sysdate(),sysdate(),15),
('The Picture of Dorian Gray','Classic',1890,6.99,5,'In the stately London home of his aunt, Lady Brandon...',sysdate(),sysdate(),16),
('Animal Farm','Classic',1945,18.50,3,'One of Orwell''s finest works, it is a political fable based on the events of Russia''s Bolshevik revolution.',sysdate(),sysdate(),17),
('The Cather In The Rye','Classic',1951,9.99,2,'The novel details two days in the life of 16-year-old Holden Caulfield after he has been expelled from prep school.',sysdate(),sysdate(),18),
('The Giving Tree','Childrens',1964,17.99,8,'The book follows the lives of an apple tree and a boy, who develop a relationship with one another.',sysdate(),sysdate(),24),
('Where The Wild Things Are','Childrens',1963,8.95,9,'This story focuses on a young boy named Max...',sysdate(),sysdate(),19),
('The Cat In The Hat','Childrens',1957,9.99,4,'The Cat in the Hat is a book where an eccentric stranger (who''s a cat!) comes into the house of two young children.',sysdate(),sysdate(),20),
('The Tale Of Peter Rabbit','Childrens',1902,7.99,6,'The widowed mother rabbit warns her four rabbit children not to enter the vegetable garden.',sysdate(),sysdate(),21),
('The Lion, The Witch, And The Wardrobe','Childrens',1950,8.99,5,'Peter, Susan, Edmund, and Lucy Pevensie are four siblings sent to live in the country with the eccentric Professor Kirke.',sysdate(),sysdate(),22),
('Charlotte''s Web','Childrens',1952,9.99,9,'A masterpiece of American childrens literature, Charlotte''s Web is a fable about a runt of a pig named Wilbur.',sysdate(),sysdate(),23),
('Where The Sidewalk Ends','Childrens',1974,19.99,7,'Where the Sidewalk Ends is a collection of quirky and imaginative poems by Shel Silverstein.',sysdate(),sysdate(),24),
('The Very Hungry Caterpillar','Childrens',1969,5.99,5,'This story follows the life of a growing caterpillar who begins as an egg.',sysdate(),sysdate(),25),
('The Neverending Story','Childrens',1979,8.99,3,'The book centres on a boy, Bastian, a strange child who is neglected by his father after the death of Bastian''s mother.',sysdate(),sysdate(),26),
('A Peoples History Of The United States','Top 9',1980,21.99,5,'A Peoples History of the United States is the only volume to tell America''s story from the point of view of women, factory workers, African-Americans, etc.',sysdate(),sysdate(),27),
('The Phantom Tollbooth','Top 9',1961,8.99,6,'The Phantom Tollbooth is the story of Milo, a very bored boy who finds a magical tollbooth in his room.',sysdate(),sysdate(),28),
('Slaughterhouse-Five','Top 9',1969,17.00,10,'Slaughterhouse-Five, an American classic, is one of the world''s great antiwar books.',sysdate(),sysdate(),29),
('Things Fall Apart','Top 9',1958,13.00,11,'It is a classic narrative about Africa''s cataclysmic encounter with Europe.',sysdate(),sysdate(),30),
('Never Let Me Go','Top 9',2005,16.00,4,'Friends Kathy, Tommy and Ruth grow up together at a seemingly idyllic boarding school.',sysdate(),sysdate(),31),
('Maus','Top 9',1991,35.00,8,'Maus depicts Spiegelman interviewing his father about his experiences as a Polish Jew and Holocaust survivor.',sysdate(),sysdate(),32),
('The Handmaid''s Tale','Top 9',1985,15.95,7,'The world of the narrator, Offred, is chilling, but she is a magnificent survivor and chronicler.',sysdate(),sysdate(),33),
('The Hitchhiker''s Guide To The Galaxy','Top 9',1980,16.00,8,'A hapless hero with astonishing luck? Ill‑tempered aliens? Pithy advice? Check, check, and check.',sysdate(),sysdate(),34),
('Infinite Jest','Top 9',1996,20.00,9,'Infinite Jest is unique; it was bred in the optimism of the dot‑com 1990s.',sysdate(),sysdate(),35),
('Origins Of American Slavery','Social Justice',2005,17.00,3,'A concise but thorough overview of how American slavery fits into larger historical processes.',sysdate(),sysdate(),36),
('Mama''s Baby, Papa''s Maybe: An American Grammar Book','Social Justice',1987,13.00,5,'Hortense Spillers argues that discourses around blackness and gender during slavery continue to determine the ways in which black bodies are read.',sysdate(),sysdate(),37),
('Neither Lost Nor Found: Slavery And The Visual Archive','Social Justice',2011,17.00,7,'Stephen Best argues that black people have often been understood as objects rather than subjects.',sysdate(),sysdate(),38),
('Black Bodies In Pain And Ecstasy','Social Justice',2003,13.00,4,'Anthony Pinn argues that black religion plays a key role in African Americans'' struggle for complex subjectivity.',sysdate(),sysdate(),39),
('The Black Body As Souvenir In American Lynching','Social Justice',2005,16.00,3,'Lynching, a phenomenon of extra‑juridical violence used as a tool of social control.',sysdate(),sysdate(),40),
('Of Du Bois And Diaspora: The Challenge Of African American Studies','Social Justice',2004,35.00,8,'Michael Gomez focuses on double consciousness, a term for the experience of African Americans.',sysdate(),sysdate(),41),
('Like I Was A Man: Chain Gangs, Gender, And Domestic Carceral Sphere In Jim Crow Georgia','Social Justice',2013,15.95,9,'Sarah Haley argues that the prison industrial complex has been a site where racialized conceptions of gender have been consolidated.',sysdate(),sysdate(),42),
('How Black Nationalism Became Sui Generis','Social Justice',2012,16.00,2,'Daryl Michael Scott explores the vicissitudes of black nationalism in the 20th century.',sysdate(),sysdate(),43),
('Whiteness As Property','Social Justice',1993,20.00,3,'Cheryl Harris explores the extent to which whiteness became a form of property.',sysdate(),sysdate(),44),
('Dune','Fantasy',1965,49.95,8,'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family.',sysdate(),sysdate(),45),
('The Witcher','Fantasy',1994,39.99,8,'The Witcher is a fantasy series of novels and short stories written by Polish author Andrzej Sapkowski.',sysdate(),sysdate(),46),
('Lord Of The Rings','Fantasy',1937,35.96,8,'At 33, the age of adulthood among hobbits, Frodo Baggins receives a magic Ring of Invisibility from his uncle Bilbo.',sysdate(),sysdate(),47),
('Harry Potter','Fantasy',1998,55.99,8,'Harry Potter, a boy who learns on his eleventh birthday that he is the orphaned son of two powerful wizards.',sysdate(),sysdate(),48),
('Twilight','Fantasy',2005,45.00,8,'The Twilight saga is a story about love. And vampires. And family.',sysdate(),sysdate(),49),
('A Song Of Ice And Fire','Fantasy',1991,50.00,8,'A Song of Ice and Fire is a series of epic fantasy novels by George R. R. Martin.',sysdate(),sysdate(),50),
('Outlander','Fantasy',1991,70.00,8,'Outlander is a series of historical romance science fiction novels by Diana Gabaldon.',sysdate(),sysdate(),51),
('Wheel Of Time','Fantasy',1984,32.00,8,'Written by Robert Jordan and completed posthumously by Brandon Sanderson.',sysdate(),sysdate(),52),
('Three-Body Problem Trilogy','Fantasy',2008,50.00,8,'From Hugo Award‑winning author Cixin Lu, the most prolific and popular science fiction writer in China.',sysdate(),sysdate(),53);
